import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";
import "./globals.css";

export const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400", // Adjust weight as needed
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={instrumentSerif.className}>
      <body className={`${instrumentSerif.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
